version: '3.8'

services:
  se-server:
    image: ghcr.io/jtcressy/agones-space-engineers:0.1
    container_name: se-ds-docker-quickstart
    restart: unless-stopped
    volumes:
      - ~/workspace/instances:/appdata/space-engineers/instances
      - ~/workspace/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ~/workspace/steamcmd:/root/.steam
    ports:
      - target: 8080
        published: 18080
        protocol: tcp
        mode: host
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment: 
      - WINEDEBUG=-all 
      - INSTANCE_NAME=DockerQuickStart